var annotated_dup =
[
    [ "KapEngine", "namespaceKapEngine.html", "namespaceKapEngine" ],
    [ "KapMirror", null, [
      [ "Experimental", null, [
        [ "GZipCompression", "classKapMirror_1_1Experimental_1_1GZipCompression.html", "classKapMirror_1_1Experimental_1_1GZipCompression" ]
      ] ],
      [ "Sylph", null, [
        [ "Address", "classKapMirror_1_1Sylph_1_1Address.html", "classKapMirror_1_1Sylph_1_1Address" ],
        [ "Client", "classKapMirror_1_1Sylph_1_1Client.html", "classKapMirror_1_1Sylph_1_1Client" ],
        [ "ClientConnection", "classKapMirror_1_1Sylph_1_1ClientConnection.html", "classKapMirror_1_1Sylph_1_1ClientConnection" ],
        [ "Connection", "classKapMirror_1_1Sylph_1_1Connection.html", "classKapMirror_1_1Sylph_1_1Connection" ],
        [ "Server", "classKapMirror_1_1Sylph_1_1Server.html", "classKapMirror_1_1Sylph_1_1Server" ],
        [ "ServerConnection", "classKapMirror_1_1Sylph_1_1ServerConnection.html", "classKapMirror_1_1Sylph_1_1ServerConnection" ],
        [ "Socket", "classKapMirror_1_1Sylph_1_1Socket.html", "classKapMirror_1_1Sylph_1_1Socket" ],
        [ "SocketException", "classKapMirror_1_1Sylph_1_1SocketException.html", "classKapMirror_1_1Sylph_1_1SocketException" ],
        [ "UdpClient", "classKapMirror_1_1Sylph_1_1UdpClient.html", "classKapMirror_1_1Sylph_1_1UdpClient" ],
        [ "UdpListener", "classKapMirror_1_1Sylph_1_1UdpListener.html", "classKapMirror_1_1Sylph_1_1UdpListener" ]
      ] ],
      [ "Telepathy", null, [
        [ "Address", "classKapMirror_1_1Telepathy_1_1Address.html", "classKapMirror_1_1Telepathy_1_1Address" ],
        [ "Client", "classKapMirror_1_1Telepathy_1_1Client.html", "classKapMirror_1_1Telepathy_1_1Client" ],
        [ "ClientConnection", "structKapMirror_1_1Telepathy_1_1ClientConnection.html", "structKapMirror_1_1Telepathy_1_1ClientConnection" ],
        [ "MagnificentReceivePipe", "classKapMirror_1_1Telepathy_1_1MagnificentReceivePipe.html", "classKapMirror_1_1Telepathy_1_1MagnificentReceivePipe" ],
        [ "MagnificentSendPipe", "classKapMirror_1_1Telepathy_1_1MagnificentSendPipe.html", "classKapMirror_1_1Telepathy_1_1MagnificentSendPipe" ],
        [ "Server", "classKapMirror_1_1Telepathy_1_1Server.html", "classKapMirror_1_1Telepathy_1_1Server" ],
        [ "Socket", "classKapMirror_1_1Telepathy_1_1Socket.html", "classKapMirror_1_1Telepathy_1_1Socket" ],
        [ "SocketException", "classKapMirror_1_1Telepathy_1_1SocketException.html", "classKapMirror_1_1Telepathy_1_1SocketException" ],
        [ "TcpClient", "classKapMirror_1_1Telepathy_1_1TcpClient.html", "classKapMirror_1_1Telepathy_1_1TcpClient" ],
        [ "TcpListener", "classKapMirror_1_1Telepathy_1_1TcpListener.html", "classKapMirror_1_1Telepathy_1_1TcpListener" ]
      ] ],
      [ "Array", "classKapMirror_1_1Array.html", null ],
      [ "ArraySegment", "classKapMirror_1_1ArraySegment.html", "classKapMirror_1_1ArraySegment" ],
      [ "Compression", "classKapMirror_1_1Compression.html", "classKapMirror_1_1Compression" ],
      [ "MessagePacking", "classKapMirror_1_1MessagePacking.html", null ],
      [ "NetworkClient", "classKapMirror_1_1NetworkClient.html", "classKapMirror_1_1NetworkClient" ],
      [ "NetworkComponent", "classKapMirror_1_1NetworkComponent.html", "classKapMirror_1_1NetworkComponent" ],
      [ "NetworkConnection", "classKapMirror_1_1NetworkConnection.html", "classKapMirror_1_1NetworkConnection" ],
      [ "NetworkConnectionToClient", "classKapMirror_1_1NetworkConnectionToClient.html", "classKapMirror_1_1NetworkConnectionToClient" ],
      [ "NetworkConnectionToServer", "classKapMirror_1_1NetworkConnectionToServer.html", "classKapMirror_1_1NetworkConnectionToServer" ],
      [ "NetworkIdentity", "classKapMirror_1_1NetworkIdentity.html", "classKapMirror_1_1NetworkIdentity" ],
      [ "NetworkManager", "classKapMirror_1_1NetworkManager.html", "classKapMirror_1_1NetworkManager" ],
      [ "NetworkMessage", "structKapMirror_1_1NetworkMessage.html", "structKapMirror_1_1NetworkMessage" ],
      [ "NetworkReader", "classKapMirror_1_1NetworkReader.html", "classKapMirror_1_1NetworkReader" ],
      [ "NetworkServer", "classKapMirror_1_1NetworkServer.html", "classKapMirror_1_1NetworkServer" ],
      [ "NetworkTime", "classKapMirror_1_1NetworkTime.html", null ],
      [ "NetworkTransform", "classKapMirror_1_1NetworkTransform.html", "classKapMirror_1_1NetworkTransform" ],
      [ "NetworkWriter", "classKapMirror_1_1NetworkWriter.html", "classKapMirror_1_1NetworkWriter" ],
      [ "ObjectDestroyMessage", "structKapMirror_1_1ObjectDestroyMessage.html", "structKapMirror_1_1ObjectDestroyMessage" ],
      [ "ObjectSpawnMessage", "structKapMirror_1_1ObjectSpawnMessage.html", "structKapMirror_1_1ObjectSpawnMessage" ],
      [ "ObjectTransformMessage", "structKapMirror_1_1ObjectTransformMessage.html", "structKapMirror_1_1ObjectTransformMessage" ],
      [ "ObjectUpdateMessage", "structKapMirror_1_1ObjectUpdateMessage.html", "structKapMirror_1_1ObjectUpdateMessage" ],
      [ "SylphTransport", "classKapMirror_1_1SylphTransport.html", "classKapMirror_1_1SylphTransport" ],
      [ "TelepathyTransport", "classKapMirror_1_1TelepathyTransport.html", "classKapMirror_1_1TelepathyTransport" ],
      [ "Transport", "classKapMirror_1_1Transport.html", "classKapMirror_1_1Transport" ]
    ] ],
    [ "MyLibrary", null, [
      [ "Example", "classMyLibrary_1_1Example.html", "classMyLibrary_1_1Example" ],
      [ "SubclassExample", "classMyLibrary_1_1SubclassExample.html", "classMyLibrary_1_1SubclassExample" ]
    ] ],
    [ "RType", null, [
      [ "Parser", null, [
        [ "Map", "classRType_1_1Parser_1_1Map.html", "classRType_1_1Parser_1_1Map" ],
        [ "Parser", "classRType_1_1Parser_1_1Parser.html", "classRType_1_1Parser_1_1Parser" ],
        [ "Summon", "classRType_1_1Parser_1_1Summon.html", "classRType_1_1Parser_1_1Summon" ]
      ] ],
      [ "Script", null, [
        [ "Debug", "classRType_1_1Script_1_1Debug.html", "classRType_1_1Script_1_1Debug" ],
        [ "Enemy", "classRType_1_1Script_1_1Enemy.html", "classRType_1_1Script_1_1Enemy" ],
        [ "Math", "classRType_1_1Script_1_1Math.html", "classRType_1_1Script_1_1Math" ],
        [ "Rectangle", "classRType_1_1Script_1_1Rectangle.html", "classRType_1_1Script_1_1Rectangle" ],
        [ "Vector2", "classRType_1_1Script_1_1Vector2.html", "classRType_1_1Script_1_1Vector2" ]
      ] ],
      [ "BoubouleEnemy", "classRType_1_1BoubouleEnemy.html", "classRType_1_1BoubouleEnemy" ],
      [ "Bullet", "classRType_1_1Bullet.html", "classRType_1_1Bullet" ],
      [ "CampaignGenerator", "classRType_1_1CampaignGenerator.html", "classRType_1_1CampaignGenerator" ],
      [ "ChangeKey", "classRType_1_1ChangeKey.html", "classRType_1_1ChangeKey" ],
      [ "EndMenu", "classRType_1_1EndMenu.html", "classRType_1_1EndMenu" ],
      [ "EnemyController", "classRType_1_1EnemyController.html", "classRType_1_1EnemyController" ],
      [ "ErrorOnStartGameMessage", "structRType_1_1ErrorOnStartGameMessage.html", "structRType_1_1ErrorOnStartGameMessage" ],
      [ "GameManager", "classRType_1_1GameManager.html", "classRType_1_1GameManager" ],
      [ "GameMenuManager", "classRType_1_1GameMenuManager.html", "classRType_1_1GameMenuManager" ],
      [ "HowToPlayAnimation", "classRType_1_1HowToPlayAnimation.html", "classRType_1_1HowToPlayAnimation" ],
      [ "HowToPlayMenu", "classRType_1_1HowToPlayMenu.html", "classRType_1_1HowToPlayMenu" ],
      [ "KeyboardMenu", "classRType_1_1KeyboardMenu.html", "classRType_1_1KeyboardMenu" ],
      [ "KeySelector", "classRType_1_1KeySelector.html", "classRType_1_1KeySelector" ],
      [ "LuaException", "classRType_1_1LuaException.html", "classRType_1_1LuaException" ],
      [ "MainMenu", "classRType_1_1MainMenu.html", "classRType_1_1MainMenu" ],
      [ "MapEnemy", "classRType_1_1MapEnemy.html", "classRType_1_1MapEnemy" ],
      [ "MapScript", "classRType_1_1MapScript.html", "classRType_1_1MapScript" ],
      [ "Menu", "classRType_1_1Menu.html", "classRType_1_1Menu" ],
      [ "MenuCampaign", "classRType_1_1MenuCampaign.html", "classRType_1_1MenuCampaign" ],
      [ "MenuManager", "classRType_1_1MenuManager.html", "classRType_1_1MenuManager" ],
      [ "MenuVolume", "classRType_1_1MenuVolume.html", "classRType_1_1MenuVolume" ],
      [ "MultiMenu", "classRType_1_1MultiMenu.html", "classRType_1_1MultiMenu" ],
      [ "ParalaxAnimation", "classRType_1_1ParalaxAnimation.html", "classRType_1_1ParalaxAnimation" ],
      [ "PlayerAuthorityMessage", "structRType_1_1PlayerAuthorityMessage.html", "structRType_1_1PlayerAuthorityMessage" ],
      [ "PlayerController", "classRType_1_1PlayerController.html", "classRType_1_1PlayerController" ],
      [ "PlayerInputMessage", "structRType_1_1PlayerInputMessage.html", "structRType_1_1PlayerInputMessage" ],
      [ "PlayerPrepareShootMessage", "structRType_1_1PlayerPrepareShootMessage.html", "structRType_1_1PlayerPrepareShootMessage" ],
      [ "PlayerShootMessage", "structRType_1_1PlayerShootMessage.html", "structRType_1_1PlayerShootMessage" ],
      [ "PlayerSkin", "classRType_1_1PlayerSkin.html", "classRType_1_1PlayerSkin" ],
      [ "Prefabs", "classRType_1_1Prefabs.html", null ],
      [ "RtypeNetworkManager", "classRType_1_1RtypeNetworkManager.html", "classRType_1_1RtypeNetworkManager" ],
      [ "SettingPlayerMenu", "classRType_1_1SettingPlayerMenu.html", "classRType_1_1SettingPlayerMenu" ],
      [ "SettingsMenu", "classRType_1_1SettingsMenu.html", "classRType_1_1SettingsMenu" ],
      [ "ShipEnemy", "classRType_1_1ShipEnemy.html", "classRType_1_1ShipEnemy" ],
      [ "SoloMenu", "classRType_1_1SoloMenu.html", "classRType_1_1SoloMenu" ],
      [ "SpawnEnemy", "structRType_1_1SpawnEnemy.html", "structRType_1_1SpawnEnemy" ],
      [ "SpriteAnimation", "classRType_1_1SpriteAnimation.html", "classRType_1_1SpriteAnimation" ],
      [ "StartGameMessage", "structRType_1_1StartGameMessage.html", "structRType_1_1StartGameMessage" ],
      [ "TentaclesBossEnemy", "classRType_1_1TentaclesBossEnemy.html", "classRType_1_1TentaclesBossEnemy" ],
      [ "UpdateStartGameKeys", "classRType_1_1UpdateStartGameKeys.html", "classRType_1_1UpdateStartGameKeys" ],
      [ "VolumeMenu", "classRType_1_1VolumeMenu.html", "classRType_1_1VolumeMenu" ]
    ] ],
    [ "FixedQueue", "classFixedQueue.html", "classFixedQueue" ],
    [ "PlayerPref", "classPlayerPref.html", null ]
];