---
--- Generated by Luanalysis
--- Created by leq.
--- DateTime: 08/11/22 16:27
---

Map.SetName("Endless fight")
Map.SetAuthor("Ewen Le Quéré")
Map.SetDescription("Endless level")
Map.SetBannerPath("Assets/Textures/Level Campaign/lvl1_img.png")
