---
--- Generated by Luanalysis
--- Created by leq.
--- DateTime: 08/11/22 11:05
---

Map.SetName("The Lair Of The Aliens")
Map.SetAuthor("Paul Dosser")
Map.SetDescription("Campaign level 1")
Map.SetBannerPath("Assets/Textures/Level Campaign/lvl1_img.png")
