---
--- Generated by Luanalysis
--- Created by leq.
--- DateTime: 08/11/22 14:55
---

Map.SetName("The House of Aliens")
Map.SetAuthor("Meredith Labejof")
Map.SetDescription("Campaign level 2")
Map.SetBannerPath("Assets/Textures/Level Campaign/lvl2_img.png")
