---
--- Generated by Luanalysis
--- Created by leq.
--- DateTime: 08/11/22 15:30
---

Map.SetName("The Villain's Lair")
Map.SetAuthor("Benjamin Delvertr")
Map.SetDescription("Campaign level 3")
Map.SetBannerPath("Assets/Textures/Level Campaign/lvl3_img.png")
