---
--- Generated by Luanalysis
--- Created by leq.
--- DateTime: 08/11/22 15:35
---

Map.SetName("The Den of Dark Shadows")
Map.SetAuthor("Chaika9")
Map.SetDescription("Campaign level 4")
Map.SetBannerPath("Assets/Textures/Level Campaign/lvl4_img.png")
