name: "Doxygen generation"
on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          submodules: "true"
      -
        name: "Install Doxygen"
        run: "sudo apt-get install doxygen -y"
        shell: bash
      - name: "Install theme"
        run: |
          git clone https://github.com/jothepro/doxygen-awesome-css.git
          cd doxygen-awesome-css
          git checkout v2.1.0
          cd ..
      -
        name: "Generate Doxygen Documentation"
        run: "doxygen Doxyfile"
        shell: bash
      -
        name: "Create .nojekyll (ensures pages with underscores work on gh pages)"
        run: "touch docs/html/.nojekyll"
        shell: bash
      -
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: ./docs/html